apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-app
          image: your-dockerhub-username/django-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-configmap
            - secretRef:
                name: django-secret
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc