# Generated by Django 5.2.4 on 2025-07-03 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_type', models.CharField(choices=[('st', 'Students'), ('t', 'Teachers')], max_length=5)),
                ('photo', models.ImageField(upload_to='images/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.department')),
            ],
        ),
    ]
