# Generated by Django 5.2.4 on 2025-07-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_department_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
