# Generated by Django 5.2.4 on 2025-07-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
